apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watermarkpodautoscaler.fullname" . }}
  labels:
    {{- include "watermarkpodautoscaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "watermarkpodautoscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watermarkpodautoscaler.selectorLabels" . | nindent 8 }}
      {{- if and (.Values.metrics.prometheus.enabled) (.Values.metrics.prometheus.ddAgentScrape) }}
      annotations:
        ad.datadoghq.com/watermarkpodautoscaler.check_names: '["prometheus"]'
        ad.datadoghq.com/watermarkpodautoscaler.init_configs: '[{}]'
        ad.datadoghq.com/watermarkpodautoscaler.instances: |
          [{
            "prometheus_url": "http://%%host%%:8383/metrics",
            "namespace":"watermarkpodautoscaler",
            "metrics": ["wpa","wpa_controller*"]
            {{- if .Values.labelsAsTags -}}
            ,
            "label_joins": {
              "wpa_controller_labels_info": {
                "labels_to_match": ["wpa_name","resource_namespace"],
                "labels_to_get": ["{{ join "\",\"" .Values.labelsAsTags }}"]
                }
              }
              {{- end }}
          }]
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "watermarkpodautoscaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --loglevel={{ .Values.logLevel }}
            - --leader-election-resource={{ .Values.leaderElectionResourceLock }}
            {{- if not .Values.metrics.prometheus.enabled }}
            - --prometheus=false
            {{- end }}
            {{- if .Values.metrics.statsd.enabled }}
            - --statsd=true
            {{- if .Values.metrics.statsd.useSocket }}
            - --statsd-addr=unix://{{ .Values.metrics.statsd.socketPath }}/{{ .Values.metrics.statsd.socketName }}
            {{- end }}
            {{- end }}
            {{- if .Values.metrics.namespace }}
            - --metrics-namespace={{ .Values.metrics.namespace }}
            {{- end }}
            {{- range $arg := .Values.extraArgs }}
            - {{ $arg }}
            {{- end }}
          env:
            - name: WATCH_NAMESPACE
            {{- if .Values.watchAllNamespaces }}
              value: ""
            {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.labelsAsTags }}
            - name: DD_LABELS_AS_TAGS
              value: {{ join " " .Values.labelsAsTags | quote }}
            {{- end }}
            {{- if and (.Values.metrics.statsd.enabled) (not .Values.metrics.statsd.useSocket) }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9440
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and (.Values.metrics.statsd.enabled) (.Values.metrics.statsd.useSocket)}}
          volumeMounts:
            - name: dsdsocket
              mountPath: {{ .Values.metrics.statsd.socketPath }}
              readOnly: true
          {{- end }}
      {{- if and (.Values.metrics.statsd.enabled) (.Values.metrics.statsd.useSocket)}}
      volumes:
        - hostPath:
            path: {{ .Values.metrics.statsd.socketPath }}
          name: dsdsocket
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
